"use client"

import { useState } from "react"
import { useParams, useRouter } from "next/navigation"
import { ArrowLeft, Send, FileText, Clock, CheckCircle, AlertCircle, Paperclip, Scale } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Textarea } from "@/components/ui/textarea"
import Link from "next/link"

interface DisputeMessage {
    direction: string;
    date: string;
    to?: string;
    subject: string;
    body: string;
    attachments?: string[];
    readAt?: string;
}

interface DisputeTimelineEvent {
    date: string;
    action: string;
    type: string;
}

interface AgentProfile {
    name: string;
    riskScore: number;
    totalDisputes: number;
    winRate: number;
    openDisputes: number;
}

interface DisputeDetail {
    id: string;
    invoiceNumber: string;
    type: string;
    amount: number;
    carrier: string;
    carrierEmail: string;
    status: string;
    date: string;
    vessel: string;
    port: string;
    evidence: string[];
    timeline: DisputeTimelineEvent[];
    messages: DisputeMessage[];
    agentProfile: AgentProfile;
}

const DISPUTES: Record<string, DisputeDetail> = {
    "DSP-992": {
        id: "DSP-992",
        invoiceNumber: "INV-2023-899",
        type: "Detention Overcharge",
        amount: 1200.00,
        carrier: "Maersk Line",
        carrierEmail: "billing@maersk.com",
        status: "sent",
        date: "2024-01-15",
        vessel: "MV Pacific Dawn",
        port: "Port of Hamburg",
        evidence: ["AIS_Track_Dec17.pdf", "Tariff_Hamburg_2024.pdf", "Invoice_INV-2023-899.pdf"],
        timeline: [
            { date: "Jan 15, 14:32", action: "Dispute generated by Sarah Chen", type: "fathom" },
            { date: "Jan 15, 14:35", action: "Dispute sent to billing@maersk.com", type: "fathom" },
            { date: "Jan 15, 16:45", action: "Email opened by carrier", type: "carrier" },
            { date: "Jan 17, 09:00", action: "Automated follow-up sent (Day 3)", type: "fathom" },
        ],
        messages: [
            {
                direction: "sent",
                date: "Jan 15, 2024 · 14:32 UTC",
                to: "billing@maersk.com",
                subject: "Formal Dispute — Invoice #INV-2023-899 — Detention Overcharge",
                body: `Dear Maersk Line Billing Department,\n\nWe are writing to formally dispute Invoice #INV-2023-899 dated January 10, 2024, for vessel MV Pacific Dawn.\n\nOur records confirm that the container was returned to terminal within the free period. AIS tracking data confirms departure from your terminal at 14:30 UTC on December 17, 2023. The invoice charges a total of 5 detention days, which does not align with the AIS-verified return timestamp.\n\nWe are requesting a credit of $1,200.00 representing the overcharged detention amount.\n\nPlease respond within 5 business days.\n\nSincerely,\nSarah Chen\nVP Operations, Pacific Shipping Co`,
                attachments: ["AIS_Track_Dec17.pdf", "Tariff_Hamburg_2024.pdf"],
                readAt: "Jan 15, 16:45 UTC",
            },
        ],
        agentProfile: {
            name: "Maersk Line",
            riskScore: 42,
            totalDisputes: 18,
            winRate: 89,
            openDisputes: 3,
        },
    },
    "DSP-994": {
        id: "DSP-994",
        invoiceNumber: "INV-2024-002",
        type: "Rate Discrepancy",
        amount: 450.00,
        carrier: "CMA CGM",
        carrierEmail: "disputes@cmacgm.com",
        status: "draft",
        date: "2024-01-22",
        vessel: "MV Baltic Star",
        port: "Port of Rotterdam",
        evidence: ["Rate_Analysis.xlsx", "Invoice_INV-2024-002.pdf"],
        timeline: [
            { date: "Jan 22, 10:00", action: "Dispute created by Sarah Chen", type: "fathom" },
        ],
        messages: [],
        agentProfile: {
            name: "CMA CGM",
            riskScore: 28,
            totalDisputes: 7,
            winRate: 71,
            openDisputes: 1,
        },
    },
}

const STATUS_BADGES: Record<string, { label: string; color: string }> = {
    draft: { label: "Draft", color: "bg-slate-500/10 text-slate-400 border-slate-500/20" },
    sent: { label: "Sent to Carrier", color: "bg-blue-500/10 text-blue-400 border-blue-500/20" },
    negotiating: { label: "Negotiating", color: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20" },
    accepted: { label: "Accepted", color: "bg-green-500/10 text-green-400 border-green-500/20" },
    rejected: { label: "Rejected", color: "bg-red-500/10 text-red-400 border-red-500/20" },
}

export default function DisputeDetailPage() {
    const params = useParams()
    const router = useRouter()
    const [reply, setReply] = useState("")
    const [showReply, setShowReply] = useState(false)
    const [expandedMsg, setExpandedMsg] = useState<number | null>(0)

    const dispute = DISPUTES[params.id as string]

    if (!dispute) {
        return (
            <div className="flex flex-col items-center justify-center min-h-[60vh] gap-4 text-center">
                <Scale className="h-16 w-16 text-slate-700" />
                <div>
                    <h2 className="text-2xl font-bold text-white mb-2">Dispute not found</h2>
                    <p className="text-slate-400 mb-5">This dispute doesn&apos;t exist or has been removed.</p>
                    <Link href="/dashboard/disputes">
                        <Button variant="outline" className="border-white/10 text-white hover:bg-white/5">
                            <ArrowLeft className="h-4 w-4 mr-2" /> Back to Disputes
                        </Button>
                    </Link>
                </div>
            </div>
        )
    }

    const fmt = (v: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(v)
    const statusCfg = STATUS_BADGES[dispute.status] ?? STATUS_BADGES.draft

    return (
        <div className="space-y-5">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                    <Button variant="ghost" size="sm" className="text-slate-400 hover:text-white" onClick={() => router.back()}>
                        <ArrowLeft className="h-4 w-4 mr-1" /> Back
                    </Button>
                    <div>
                        <div className="flex items-center gap-2">
                            <h2 className="text-2xl font-bold text-white">Dispute #{dispute.id}</h2>
                            <Badge className={`border text-xs ${statusCfg.color}`}>{statusCfg.label}</Badge>
                        </div>
                        <p className="text-slate-400 text-sm mt-0.5">
                            {dispute.invoiceNumber} · {dispute.carrier} · {dispute.vessel} · {dispute.port}
                        </p>
                    </div>
                </div>
                <div className="flex gap-2">
                    <Button variant="outline" size="sm" className="border-white/10 text-slate-400 hover:text-white">
                        📩 Send Follow-Up
                    </Button>
                    <Button size="sm" className="bg-green-600 hover:bg-green-500 text-white">
                        ✓ Mark Resolved
                    </Button>
                </div>
            </div>

            {/* Main layout */}
            <div className="grid grid-cols-12 gap-5">

                {/* Left — Main content */}
                <div className="col-span-12 lg:col-span-8 space-y-4">

                    {/* Overview card */}
                    <div className="rounded-xl border border-white/10 bg-slate-900/50 p-5">
                        <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wide mb-4">Overview</h3>
                        <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                            {[
                                { label: "Dispute ID", value: dispute.id },
                                { label: "Invoice", value: dispute.invoiceNumber },
                                { label: "Vessel", value: dispute.vessel },
                                { label: "Carrier", value: dispute.carrier },
                                { label: "Disputed Amount", value: fmt(dispute.amount) },
                                { label: "Opened", value: dispute.date },
                            ].map(({ label, value }) => (
                                <div key={label}>
                                    <p className="text-xs text-slate-500 mb-0.5">{label}</p>
                                    <p className="text-sm font-semibold text-white font-mono">{value}</p>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Communication thread */}
                    <div className="rounded-xl border border-white/10 bg-slate-900/50 overflow-hidden">
                        <div className="bg-slate-800/60 px-5 py-3 border-b border-white/10 flex items-center justify-between">
                            <span className="text-sm font-semibold text-white">Communication Thread</span>
                            <Button size="sm" variant="ghost" className="text-sky-400 hover:text-white text-xs" onClick={() => setShowReply(!showReply)}>
                                + Reply
                            </Button>
                        </div>

                        <div className="divide-y divide-white/5">
                            {dispute.messages.length === 0 && (
                                <div className="p-8 text-center text-slate-500 text-sm">
                                    No messages sent yet. This dispute is in draft.
                                </div>
                            )}

                            {dispute.messages.map((msg, i: number) => (
                                <div key={i} className={`p-5 ${msg.direction === "sent" ? "border-l-4 border-l-sky-500/60" : "border-l-4 border-l-green-500/60"}`}>
                                    <div className="flex items-start justify-between mb-3">
                                        <div>
                                            <div className={`text-xs font-mono font-semibold ${msg.direction === "sent" ? "text-sky-400" : "text-green-400"}`}>
                                                {msg.direction === "sent" ? "OUTGOING" : "INCOMING"} — {msg.date}
                                            </div>
                                            <div className="text-xs text-slate-500 mt-0.5">
                                                {msg.direction === "sent" ? "To:" : "From:"} {msg.direction === "sent" ? msg.to : dispute.carrierEmail}
                                            </div>
                                            <div className="text-sm font-semibold text-white mt-1">{msg.subject}</div>
                                        </div>
                                        {msg.readAt && (
                                            <div className="text-xs text-green-400 flex items-center gap-1 shrink-0 ml-4">
                                                <CheckCircle className="h-3 w-3" />
                                                Opened {msg.readAt}
                                            </div>
                                        )}
                                    </div>

                                    {/* Message body — collapsible */}
                                    <div className={`text-sm text-slate-400 leading-relaxed whitespace-pre-line overflow-hidden transition-all ${expandedMsg === i ? "" : "max-h-16"}`}>
                                        {msg.body}
                                    </div>
                                    <button
                                        className="text-xs text-sky-400 mt-2 hover:text-sky-300"
                                        onClick={() => setExpandedMsg(expandedMsg === i ? null : i)}
                                    >
                                        {expandedMsg === i ? "Collapse letter ▲" : "Expand full letter ▼"}
                                    </button>

                                    {msg.attachments && msg.attachments.length > 0 && (
                                        <div className="flex flex-wrap gap-2 mt-3">
                                            {msg.attachments.map((att: string) => (
                                                <div key={att} className="flex items-center gap-1.5 rounded-md bg-slate-800 border border-white/10 px-2.5 py-1.5 text-xs text-slate-300 hover:border-sky-500/40 cursor-pointer">
                                                    <Paperclip className="h-3 w-3 text-slate-500" />
                                                    {att}
                                                </div>
                                            ))}
                                        </div>
                                    )}
                                </div>
                            ))}
                        </div>

                        {/* Reply composer */}
                        {showReply && (
                            <div className="p-5 border-t border-white/10 bg-slate-900/30 space-y-3">
                                <div className="text-xs text-slate-400 font-medium">Reply to {dispute.carrierEmail}</div>
                                <Textarea
                                    placeholder="Type your response..."
                                    value={reply}
                                    onChange={(e) => setReply(e.target.value)}
                                    className="bg-slate-900 border-white/10 text-white placeholder:text-slate-500 min-h-[120px]"
                                />
                                <div className="flex justify-between items-center">
                                    <Button variant="ghost" size="sm" className="text-slate-400 text-xs">
                                        <Paperclip className="h-3 w-3 mr-1" /> Attach Evidence
                                    </Button>
                                    <div className="flex gap-2">
                                        <Button size="sm" variant="ghost" className="text-slate-400" onClick={() => setShowReply(false)}>Cancel</Button>
                                        <Button size="sm" className="bg-sky-600 hover:bg-sky-500 text-white">
                                            <Send className="h-3.5 w-3.5 mr-1.5" /> Send Reply
                                        </Button>
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>
                </div>

                {/* Right sidebar */}
                <div className="col-span-12 lg:col-span-4 space-y-4">

                    {/* Evidence Package */}
                    <div className="rounded-xl border border-white/10 bg-slate-900/50 p-5 space-y-3">
                        <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                            <FileText className="h-4 w-4 text-sky-400" /> Evidence Package
                        </h3>
                        {dispute.evidence.map((doc: string) => (
                            <div key={doc} className="flex items-center gap-2 rounded-lg bg-slate-800/60 border border-white/10 px-3 py-2 hover:border-sky-500/30 cursor-pointer transition-colors">
                                <Paperclip className="h-3.5 w-3.5 text-slate-500 shrink-0" />
                                <span className="text-xs text-slate-300 flex-1">{doc}</span>
                                <span className="text-xs text-sky-400">View</span>
                            </div>
                        ))}
                        <Button size="sm" variant="outline" className="w-full border-white/10 text-slate-400 hover:text-white text-xs mt-1">
                            📦 Download All as ZIP
                        </Button>
                    </div>

                    {/* Timeline */}
                    <div className="rounded-xl border border-white/10 bg-slate-900/50 p-5 space-y-4">
                        <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                            <Clock className="h-4 w-4 text-sky-400" /> Timeline
                        </h3>
                        <div className="relative pl-4 border-l border-white/10 space-y-4">
                            {dispute.timeline.map((event, i: number) => (
                                <div key={i} className="relative">
                                    <div className={`absolute -left-[21px] top-1.5 h-2.5 w-2.5 rounded-full border-2 border-slate-950 ${event.type === "fathom" ? "bg-sky-500" : "bg-green-500"}`} />
                                    <p className="text-xs text-slate-600">{event.date}</p>
                                    <p className="text-xs text-slate-300">{event.action}</p>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Agent Profile */}
                    <div className="rounded-xl border border-white/10 bg-slate-900/50 p-5 space-y-3">
                        <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                            <AlertCircle className="h-4 w-4 text-yellow-400" /> Agent Profile
                        </h3>
                        <div className="text-sm font-bold text-white">{dispute.agentProfile.name}</div>
                        <div className="grid grid-cols-2 gap-3 text-xs">
                            <div className="rounded-lg bg-slate-800/60 p-2.5 text-center">
                                <div className="font-mono font-bold text-white text-lg">{dispute.agentProfile.riskScore}</div>
                                <div className="text-slate-500">Risk Score</div>
                            </div>
                            <div className="rounded-lg bg-slate-800/60 p-2.5 text-center">
                                <div className="font-mono font-bold text-green-400 text-lg">{dispute.agentProfile.winRate}%</div>
                                <div className="text-slate-500">Win Rate</div>
                            </div>
                        </div>
                        <div className="text-xs text-slate-500">
                            {dispute.agentProfile.totalDisputes} total disputes with this carrier
                        </div>
                        {dispute.agentProfile.openDisputes > 1 && (
                            <div className="rounded-lg bg-yellow-500/10 border border-yellow-500/20 px-3 py-2 text-xs text-yellow-400">
                                ⚠️ {dispute.agentProfile.openDisputes} other active disputes
                            </div>
                        )}
                    </div>

                    {/* Related Invoice */}
                    <div className="rounded-xl border border-white/10 bg-slate-900/50 p-5">
                        <h3 className="text-sm font-semibold text-white mb-3">Related Invoice</h3>
                        <Link href={`/dashboard/invoices/1`} className="text-sky-400 text-sm hover:text-sky-300 hover:underline font-mono">
                            {dispute.invoiceNumber} →
                        </Link>
                    </div>
                </div>
            </div>
        </div>
    )
}
